account/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)

app_name = 'account'

urlpatterns = [
    path('', include(router.urls)),
]

account/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

ip3nalog/urls.py
"""ip3nalog URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('account/', include('account.urls')),
    path('api/', include('account.api.urls', namespace='api')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('send_feedback/', views.send_feedback, name='send_feedback'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ip_nalog = models.PositiveIntegerField(blank=True, null=True)

landing/models.py
from django.db import models


class VisibleBlockManager(models.Manager):
    def get_queryset(self):
        return super(VisibleBlockManager, self).get_queryset().filter(status='visible').order_by('sorting')


class VisibleMenuManager(models.Manager):
    def get_queryset(self):
        return super(VisibleMenuManager, self).get_queryset().filter(menu_status='visible').order_by('sorting')


class Block(models.Model):
    STATUS_CHOICES = (
        ('visible', 'Visible'),
        ('invisible', 'Invisible'),
    )
    sorting = models.PositiveIntegerField(default=999)
    block_id = models.CharField(max_length=20, default='default')
    block_title = models.CharField(max_length=250)
    title = models.CharField(max_length=250, blank=True)
    content = models.TextField(blank=True)
    image = models.ImageField(upload_to='uploads/', blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='invisible')
    menu_status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='invisible')
    objects = models.Manager()
    visible_block = VisibleBlockManager()
    visible_menu = VisibleMenuManager()

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    ip_nalog = forms.CharField(label='ИП налог')

    class Meta:
        model = Profile
        fields = ('ip_nalog',)

landing/forms.py
from django import forms


class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=100, label='',
                           widget=forms.TextInput(attrs={'class': "form-input", 'placeholder': 'Ваше имя'}))
    email = forms.EmailField(label='',
                             widget=forms.TextInput(attrs={'class': "form-input", 'placeholder': 'Email'}))

account/api/views.py
from django.contrib.auth.models import User
from rest_framework import viewsets, permissions
from rest_framework.response import Response
from rest_framework.decorators import action
from .serializers import UserSerializer


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """API endpoints for User model."""
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]

    @action(detail=False, methods=['post', 'get'])
    def active(self, request, *args, **kwargs):
        """API endpoint that allows to view active users."""
        active_users = self.queryset.filter(is_active=True)
        serializer = self.serializer_class(instance=active_users, many=True)
        return Response(serializer.data)

account/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm
from .models import Profile


@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html')


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})

landing/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from .forms import FeedbackForm


def landing(request):
    return render(request, 'landing/block/block.html')


def send_feedback(request):
    form = FeedbackForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        subject = f'Новая заявка на сайте ip3nalog.ru.'
        message = f'Привет! На сайте https://ip3nalog.ru/ оставили новую заявку.\n\n' \
                    f'Контактные данные пользователя: \n\n' \
                    f'Имя: {cd["name"]} \n\n' \
                    f'Email: {cd["email"]} \n\n'
        send_mail(subject, message, 'admin@admin.com', ['admin@admin.com'])
    return redirect('landing:landing')

landing/templates/base.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!--metatextblock-->
        <title>Снижаем налоговую ставку для ИП до 3%</title>
        <meta name="description" content="Льготная программа в Удмуртии для компаний из других регионов">
        <meta property="og:url" content="https://ip3nalog.ru">
	    <meta property="og:title" content="Снижаем налоговую ставку для ИП до 3%">
	    <meta property="og:description" content="Льготная программа в Удмуртии для компаний из других регионов">
        <meta property="og:type" content="website">
        <meta property="og:image" content="{% static 'landing/images/Frame_8.jpg' %}">
        <link rel="cannonical" href="https://ip3nalog.ru">
        <!--/metatextblock-->

        <link rel="shortcut icon" href="{% static 'landing/images/favicon.ico' %}" type="image/x-icon">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
              integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'landing/css/style.css' %}">
    </head>

    <body>
        <header>
            <nav>
                <div class="nav__logo">
                    <a href="/">
                        <img src="{% static 'landing/images/logotype.svg' %}" alt="">
                        безопасное и законное снижение налогов
                    </a>
                </div>
                <div class="nav__menu">
                    <ul>
                        {% for item in menu_blocks %}
                            <li><a href="/#{{ item.block_id }}">{{ item.block_title }}</a></li>
                        {% endfor%}
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'dashboard' %}">Профиль</a></li>
                            <li><a href="{% url 'logout' %}">Выйти</a></li>
                        {% else %}
                            <li><a href="{% url 'login' %}">Войти</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="nav__cta">
                    <button type="button" class="button" data-toggle="modal" data-target="#modalForm">
                        Подать заявку
                    </button>
                </div>
                <div class="nav__burger">
                    <a href="#" class="toggle-menu"><img src="{% static 'landing/images/menu.svg' %}" alt=""></a>
                </div>
            </nav>

            <div class="navbar__mobile">
                <a href="#" class="close-menu"><img src="{% static 'landing/images/cancel.svg' %}" alt=""></a>
                <img src="{% static 'landing/images/logo_white.svg' %}" alt="">
                <ul>
                    {% for item in menu_blocks %}
                        <li><a href="/#{{ item.block_id }}">{{ item.block_title }}</a></li>
                    {% endfor%}
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'dashboard' %}">Профиль</a></li>
                        <li><a href="{% url 'logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Войти</a></li>
                    {% endif %}
                </ul>
            </div>
        </header>
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <a href="/" class="footer__logo">
                            <img src="{% static 'landing/images/logo_footer.svg' %}" alt="">
                            безопасное и законное<br>снижение налогов
                        </a>
                    </div>
                    <div class="col-12 col-md-6 footer__policity">
                        <a href="#">политика в отношении обработки<br>персональных данных</a>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Modal -->
        <div class="modal fade" id="modalForm" tabindex="-1" aria-labelledby="modalFormLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <div class="modal-body">
                        <img src="{% static 'landing/images/go.webp' %}" class="img-fluid" alt="">
                        <h5>Поможем сэкономить на налогах в 6 раз</h5>
                        <p>Оставьте контактные данные, чтобы мы связались с вами и договорились о встрече
                        </p>
                        <form method="post" action="{% url 'landing:send_feedback' %}">
                            {{ feedback_form.as_p }}
                            {% csrf_token %}
                            <div><button type="submit" class="button">Отправить</button></div>
                        </form>
                        <p class="modal__footer">Нажимая на кнопку «Отправить», вы соглашаетесь на обработку персональных данных в соответствии с <a href="#">политикой конфиденциальности</a></p>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

        <script>
            $(function () {
                $('.toggle-menu').click(function(e) {
                    e.preventDefault();
                    $('.navbar__mobile').toggleClass('show');
                })
                $('.close-menu').click(function(e) {
                    e.preventDefault();
                    $('.navbar__mobile').removeClass('show');
                })
            });
        </script>
    </body>
</html>

landing/templates/landing/block/block.html
{% extends "base.html" %}

{% block content %}

    {% for block in blocks %}
        {% with template_name=block.block_id|stringformat:"s"|add:".html" %}
            {% include "landing/block/"|add:template_name %}
        {% endwith %}
    {% endfor %}

{% endblock %}

landing/templates/landing/block/calltoaction.html
<section id="{{ block.block_id }}">
    <div class="container">
        <div class="calltoaction__inner">
            <div class="row">
                <div class="col-12 col-sm-6">
                    {% if block.title %}
                        <h2>{{ block.title }}</h2>
                    {% endif %}
                </div>
                <div class="col-12 col-sm-6">
                    {% if block.content %}
                        {{ block.content|safe }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

landing/templates/landing/block/default.html
<section id="{{ block.block_id }}" class="landing-block">
    <div class="container">
        <div class="row">
            <div class="col-12">
                {% if block.title %}
                    <h2>{{ block.title }}</h2>
                {% endif %}
                {% if block.content %}
                    {{ block.content|safe }}
                {% endif %}
                {% if block.image %}
                    <img src="{{ block.image.url }}" class="img-fluid">
                {% endif %}
            </div>
        </div>
    </div>
</section>

landing/templates/landing/block/economy.html
<section id="{{ block.block_id }}" class="landing-block">
    <div class="container">
        <div class="grid">
            <div class="title">
                {% if block.title %}
                    <h2>{{ block.title }}</h2>
                {% endif %}
            </div>
            <div class="image">
                <h5>Ваш месячный оборот</h5>
                <input type="text" class="form-input">
                <div class="economy__table">
                    <div class="economy__table-item">
                        <div>Ваш годовой оборот</div>
                        <div>360 000 р.</div>
                    </div>
                    <div class="economy__table-item">
                        <div>Налог в год по ставке 6%</div>
                        <div>360 000 р.</div>
                    </div>
                    <div class="economy__table-item">
                        <div><b>Налог в месяц по ставке 3%</b></div>
                        <div><b>360 000 р.</b></div>
                    </div>
                    <div class="economy__table-item">
                        <div><h4>Ваша выгода в год</h4></div>
                        <div>360 000 р.</div>
                    </div>
                </div>
            </div>
            <div class="text">
                {% if block.content %}
                    {{ block.content|safe }}
                {% endif %}
            </div>
        </div>
    </div>
</section>

landing/templates/landing/block/header.html
<section id="{{ block.block_id }}" class="landing-block">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6">
                {% if block.title %}
                    <h1>{{ block.title }}</h1>
                {% endif %}
                {% if block.content %}
                    {{ block.content|safe }}
                {% endif %}
            </div>
            <div class="col-12 col-lg-6">
                {% if block.image %}
                    <img src="{{ block.image.url }}" class="img-fluid">
                {% endif %}
            </div>
        </div>
    </div>
</section>

landing/templates/landing/block/programm.html
<section id="{{ block.block_id }}" class="landing-block">
    <div class="container">
        <div class="grid">
            <div class="title">
                {% if block.title %}
                    <h2>{{ block.title }}</h2>
                {% endif %}
            </div>
            <div class="image text-center">
                {% if block.image %}
                    <img src="{{ block.image.url }}" class="img-fluid">
                {% endif %}
                </div>
            <div class="text">
                {% if block.content %}
                    {{ block.content|safe }}
                {% endif %}
            </div>
        </div>
    </div>
</section>